- .travis.yml
- package.json
- packages/node-xmpp-component/.gitignore
- packages/node-xmpp-component/.npmignore
- packages/node-xmpp-component/.travis.yml
- packages/node-xmpp-component/README.md
- packages/node-xmpp-component/examples/answer_bot.js
- packages/node-xmpp-component/examples/cluster/README.md
- packages/node-xmpp-component/examples/cluster/config.js
- packages/node-xmpp-component/examples/cluster/server.js
- packages/node-xmpp-component/examples/cluster/worker.js
- packages/node-xmpp-component/examples/question_component.js
- packages/node-xmpp-component/examples/send_message_component.js
- packages/node-xmpp-component/index.js
- packages/node-xmpp-component/lib/Component.js
- packages/node-xmpp-component/package.json
- packages/node-xmpp-component/test/integration/prosody.js
- packages/node-xmpp-component/test/resources/prosody.cfg.lua
- packages/node-xmpp-component/test/unit/connection.js
integration tests are disabled for now
I will re-enable them along with node-xmpp-client integration tests 
See https://github.com/node-xmpp/node-xmpp/issues/297
> move node-xmpp-component here

- packages/node-xmpp-client/lib/websockets.js
- packages/node-xmpp-client/package.json
https://github.com/alexhultman/uWebSockets looks interesting as well
> client: replace faye-websocket with ws

- .travis.yml
- package.json
mocha-phantomjs-core/npm run test:browser randomly fails with phantomjs 2.0
> use phantomjs 2.1

- packages/component-core/README.md
- packages/component-core/index.js
- packages/component-core/package.json
- packages/component/README.md
- packages/component/example.js
- packages/component/index.js
- packages/component/package.json
- packages/connection-tcp/ava/Connection.js
- packages/connection-tcp/index.js
- packages/connection-tcp/lib/StreamParser.js
- packages/connection/index.js
- packages/reconnect/README.md
- packages/reconnect/index.js
- packages/reconnect/package.json
* renames `@xmpp/component` to `@xmpp/component-core`
* adds `@xmpp/reconnect` plugin
* adds `@xmpp/component` which includes `component-core` and `reconnect`
> @xmpp/reconnect

- .travis.yml
- packages/plugins/disco-info/index.js
- packages/plugins/entity-capabilities/ava/test.js
- packages/plugins/entity-capabilities/index.js
- packages/plugins/index.js
- packages/plugins/iq-callee/index.js
- packages/plugins/iq-caller/index.js
- packages/plugins/package.json
- packages/plugins/ping/handle.js
- packages/plugins/ping/index.js
- packages/plugins/ping/query.js
- packages/plugins/stanza-router/index.js
- packages/plugins/time/handle.js
- packages/plugins/time/index.js
- packages/plugins/time/query.js
- packages/plugins/version/handle.js
- packages/plugins/version/index.js
- packages/plugins/version/query.js
> @xmpp/plugins

- packages/client-core/index.js
- packages/client/examples/tcp.js
- packages/client/examples/websocket.js
- packages/client/lib/plugins.js
- packages/component-core/index.js
- packages/component/example.js
- packages/connection-tcp/index.js
- packages/console/README.md
- packages/console/app.js
- packages/plugins/tcp/lib/TCP.js
- packages/plugins/tls/index.js
- packages/plugins/tls/lib/TLS.js
https://xmpp.org/extensions/xep-0368.html
> add XMPP over TLS support

- packages/client-core/index.js
- packages/component-core/index.js
- packages/component/example.js
- packages/connection-tcp/index.js
- packages/connection/index.js
- packages/console/README.md
- packages/console/cli.js
- packages/console/lib/Console.js
- packages/console/public/index.html
- packages/console/public/script.js
- packages/console/web.js
- packages/debug/README.md
- packages/plugins/reconnect/index.js
- packages/plugins/websocket/lib/WebSocket.js
* optional lang attribute
* replace `waitHader` with `responseHeader`
* get reponse lang attribute
* console: make `endpoint` optional
* allow deployment of web console
* only try to reconnect after successful online
* fix various issues
> small fixes

- packages/plugins/sasl/lib/SASLPlugin.js
> Do not insert white characters to SASL exchange

- packages/connection/index.js
- packages/plugins/iq-caller/index.js
> Better stanza id generator

- packages/xmpp.js/index.js
- packages/xmpp.js/package.json
https://www.npmjs.com/package/xmpp.js
only exporting `@xmpp/client` for now
> add xmpp.js package

- docs/component.md
just stumbled across this typo while trying the example
> fixed small typo in component.md

- packages/plugins/sasl/index.js
fix for https://github.com/xmppjs/xmpp.js/pull/457
I made a temporary fix, as I'll rework sasl mechanism choosing soon
> sasl: use available instead of offered mechanisms

- docs/xml.md
- packages/connection/index.js
- packages/plugins/disco/README.md
- packages/plugins/disco/callee.js
- packages/plugins/disco/caller.js
- packages/plugins/disco/test.js
- packages/plugins/entity-capabilities/README.md
- packages/plugins/entity-capabilities/index.js
- packages/plugins/entity-capabilities/test.js
- packages/plugins/iq-callee/README.md
- packages/plugins/iq-callee/index.js
- packages/plugins/iq-caller/index.js
- packages/plugins/ping/README.md
- packages/plugins/ping/callee.js
- packages/plugins/ping/caller.js
- packages/plugins/time/README.md
- packages/plugins/time/callee.js
- packages/plugins/time/caller.js
- packages/plugins/version/README.md
- packages/plugins/version/callee.js
- packages/plugins/version/caller.js
- server/prosody.cfg.lua
fixes:
* fix an error in @xmpp/xml documentation
new plugins:
* disco/callee
* disco/caller
* entity-capabilities
* iq-callee
* ping/callee
* ping/caller
* time/callee
* time/caller
* version/callee
* version/caller
> reintroduce iq-callee plugin and various plugins

- .travis.yml
- packages/connection-tcp/index.js
- packages/resolve/lib/dns.js
- packages/tls/lib/Connection.js
- server/prosody.cfg.lua
- test/client.js
https://issues.prosody.im/1430
> Use prosody 0.11 for e2e tests

- packages/client/README.md
- packages/client/example.js
- packages/component-core/lib/Component.js
- packages/component-core/test/send.js
- packages/component/README.md
- packages/component/example.js
- packages/connection/index.js
- packages/debug/README.md
- packages/debug/index.js
- packages/debug/package.json
- packages/xml/README.md
- packages/xml/lib/Parser.js
- packages/xml/lib/serialize.js
- packages/xml/test/Parser.js
Also fixes a bunch of small-ish issues.
> debug: hide sensitive information

- .gitignore
- packages/client/browser.js
- packages/client/index.js
- packages/client/package.json
- packages/client/react-native.js
- packages/stream-features/route.js
- packages/stream-management/README.md
- packages/stream-management/index.js
- packages/stream-management/package.json
- packages/stream-management/test.js
- packages/time/README.md
- packages/xmpp.js/package.json
- protocols.md
- server/prosody-modules/mod_smacks/README.markdown
- server/prosody-modules/mod_smacks/mod_smacks.lua
- server/prosody.cfg.lua
does not support requesting acks yet
> XEP-0198: Stream Management

- README.md
- packages/connection/index.js
- packages/connection/test/test.js
- packages/events/lib/promise.js
Fixes https://github.com/xmppjs/xmpp.js/issues/870
> connection: fix stop() triggering a unhandled rejection in some cases

- packages/client/README.md
- packages/component/README.md
- packages/connection/index.js
- packages/connection/test/send.js
- packages/connection/test/stop.js
- packages/connection/test/test.js
- packages/websocket/test/test.js
> connection: send multiple stanzas

- packages/connection/index.js
- packages/starttls/package.json
- packages/starttls/starttls.js
- packages/tls/lib/Socket.js
- packages/tls/test.js
@netmikey could you review and test this?
> Openfire TLS 1.3 workaround

- packages/jid/lib/escaping.js
https://github.com/xmppjs/xmpp.js/issues/931
> Removing invalid regex backreference from escaping

- ava.config.js
- packages/error/index.js
- packages/error/test.js
- packages/sasl/index.js
- packages/sasl/test.js
Fixes https://github.com/xmppjs/xmpp.js/issues/952
> Use getChildElements to fix bugs in SASL and XMPPError
