package.json, packages/node-xmpp-client/lib/session.js, packages/node-xmpp-client/test/reconnect.js, packages/node-xmpp-client/test/sasl.js, packages/node-xmpp-client/test/stream.js, packages/node-xmpp-server/test/integration/C2S/BOSH.js, packages/node-xmpp-server/test/integration/C2S/TCP.js, packages/node-xmpp-server/test/integration/C2S/authentication.js, packages/node-xmpp-server/test/integration/C2S/bind.js, packages/node-xmpp-server/test/integration/S2S/Router.js, packages/node-xmpp-server/test/integration/component.js, packages/node-xmpp/test/server-event-test.js, packages/streamparser/index.js, packages/xml/index.js, packages/xml/lib/createStanza.js, test/browser/index.html
* allow to set port without hostname on `node-xmpp-client` configuration (defaults to localhost)
* stop using standard ports for tests
* add more events to streamparser
* smarter `@xmpp/xml` package
=> stop using standard ports for tests

.travis.yml, README.md, lerna.json, package.json, packages/component/README.md, packages/component/example.js, packages/component/index.js, packages/component/package.json, packages/connection-tcp/ava/Connection.js, packages/connection-tcp/index.js, packages/connection-tcp/lib/StreamParser.js, packages/connection-tcp/package.json, packages/connection/ava/test.js, packages/connection/index.js, packages/connection/package.json, test/ava/component.js
brand new `@xmpp/component` modular package
Adds the following packages
- `@xmpp/connection`
- `@xmpp/connection-tcp`
- `@xmpp/component`
The goal is to reuse those for client/server as it's already done in https://github.com/node-xmpp/node-xmpp/pull/309
Todo
- now
- tests
- doc
- fix `FIXME`s and `TODO`s
- later
- `@xmpp/component-core`
- `@xmpp/reconnect`
- `@xmpp/component-connection` [XEP-0225](https://xmpp.org/extensions/xep-0225.html)
- `@xmpp/component-protocol` [XEP-0114](https://xmpp.org/extensions/xep-0114.html)
and  have `@xmpp/component` use them. Or maybe just files.
Please comment on the API as it would be the same for client and server.
``` javascript
'use strict'
const Component = require('@xmpp/component')
const entity = new Component()
// emitted for any error …
```
=> @xmpp/component

packages/node-xmpp-server/test/unit/S2S/Router.js, packages/node-xmpp-server/test/unit/S2S/incoming.js, packages/xml/index.js, packages/xml/test/index.js
The recent publish broke us. This fix resolves our issues.
In our usage (which could be a bit non-standard), `ltx.parse` seems to somehow be pointing to `xml/lib/parse.js` instead of `ltx/lib/parse.js`. This fix results in it pointing to the correct parse function in our test suite. Admittedly, it does seem odd that exposing `ltx.tag` would somehow end up with the wrong parse function being used. But, not exposing something like this seems like a safer thing to do regardless.
=> Stop leaking ltx.tag for possible mutation.

packages/client/lib/plugins.js, packages/plugins/session-establishment/index.js
plugin for https://tools.ietf.org/html/draft-cridland-xmpp-session-01 and adds it to `@xmpp/client` for backward compatibility
=> client: session-establishment

packages/console/README.md, packages/console/app.js
Allow to use `xmpp-console` with `rlwrap` to enable persistent history.
Unfortunately it shows some bugs so it's not ready to be advertised yet. Also I'd prefer to have the persistent history functionality included in xmpp-console but it's not trivial as Node.js readline module doesn't allow to do that easily.
See https://github.com/nodejs/node/blob/db1087c9757c31a82c50a1eba368d8cba95b57d0/lib/internal/repl.js for inspiration.
Here is the documentation I wrote for the `README.md`.
Just [like Node.js REPL](https://nodejs.org/api/repl.html#repl_using_the_node_js_repl_with_advanced_line_editors) it is possible to use xmpp-console with `rlwrap` to enable advanced line-editors.
```
env NODE_NO_READLINE=1 rlwrap xmpp-console xmpp:component.localhost:5347 password
```
=> console: enable NODE_NO_READLINE env var

packages/node-xmpp-client/lib/websockets.js
This PR allows passing of websocket options. This allows configuration of the Faye websocket. In my case, I am using this to enable permessage-deflate compression. I opened another pull for this in the wrong repo previously (https://github.com/node-xmpp/client/pull/210)
=> Allow passing websocket options through

packages/plugins/websocket/lib/Connection.js
`xml.Element` is a constructor and needs to be called with `new`
=> Fixed WebSocket stream closing

packages/xml/lib/parse.js
`tag()` expects substitutions as subsequent arguments, not in Array
=> Fix xml/parse

.eslintrc, .travis.yml, Makefile, package.json, packages/client/example.js, packages/client/lib/Client.js, packages/component-core/index.js, packages/component-core/test/test.js, packages/component/example.js, packages/connection-tcp/index.js, packages/connection/index.js, packages/debug/index.js, packages/events/index.js, packages/events/lib/EventEmitter.js, packages/events/lib/TimeoutError.js, packages/events/lib/delay.js, packages/events/lib/promise.js, packages/events/lib/timeout.js, packages/events/package.json, packages/events/yarn.lock, packages/plugins/bind/index.js, packages/plugins/sasl/index.js, packages/plugins/stream-features/index.js, packages/plugins/tls/lib/Connection.js, packages/xml/test/parse.js, test/client.js, test/component.js
cc @ggozad @smokku 
Use this to log status.
```js
client.on('status', (status, value) => {
console.log('status', value ? value.toString() : '')
})
```
See Breaking changes
opening, starting, closing, authenticating, ...
`entity.write()` now returns a promise and replace `promiseWrite()`
`authenticate`, `bind`, ... events do not pass a function anymore, use `handle` instead of `on` to handle those.
Example
```js
client.handle('authentication', (authenticate) => {
return authenticate('foo', 'bar')
// optional
// handle error if you want
// but make sure to throw it afterwards to pass it along the `.start` promise chain
.catch(err => {
console.error('authentication failed', err.toString())
throw err
})
})
```
https://github.com/node-xmpp/node-xmpp/pull/418#issuecomment-305183091
I'm not …
=> events, handlers and status

packages/client/example.js, packages/connection/index.js, packages/plugins/reconnect/index.js, packages/plugins/resolve/index.js, test/client.js
* removes `starting` status
* removes `stopping` status
* fix client reconnection when resolve plugin is enabled (introduced in last PR)  +  add client reconnection tests
=> fix client reconnection when resolve plugin is enabled

packages/client/README.md
I realized that it doesn't show ONLINE on buddies, when I add this, it is working great. By the way, I have an other 'buddy' account which is online via Adium, and Adium XML console shows that xmppjs client sends a presence with a type 'unavailable' like this:
```
<presence xmlns='jabber:client' type='unavailable' from='testuser1@example.net/example' to='testuser2@example.net'/>
```
Maybe this is the origin of the problem.
=> send presence when it gets online

packages/client/example.js
`xml('body', 'hello world')` actually translates to `<body xmlns="hello world"/> `, because of how `@xmpp/xml` is actually implemented: `function x(name, attrs, ...children)`. It should be `xml('body', null, 'hello world')`, so 'hello world' actually ends in a `children` argument. Then it actually translates to `<body>hello world</body>` and can be received by some client.
=> fix error in docs

packages/test/context.js
In the last big refactoring fakeIncomingSet appears to have been lost.
=> Add fakeIncomingSet to test framework

packages/test/context.js
This fixes a mistake from #640: fakeIncomingSet should not take `context` as a parameter, but use `this` instead.
=> Correct fakeIncomingSet API

packages/connection-tcp/index.js, packages/connection-tcp/package.json, packages/connection/index.js, packages/connection/lib/util.js, packages/connection/package.json, packages/tls/lib/Connection.js, packages/tls/package.json, test/see-other-host.js, yarn.lock
Used at least by Tigase for clustered WebSocket/BOSH/TCP.
https://github.com/tigase/tigase-server/search?q=see_other_host_strategy&unscoped_q=see_other_host_strategy
See also https://github.com/xmppjs/xmpp.js/issues/781
=> connection: implement see-other-host

packages/connection/index.js, packages/connection/test/onData.js, packages/connection/test/parserError.js, packages/xml/index.js, packages/xml/lib/Parser.js, packages/xml/lib/XMLError.js
- Fixes a serious bug with exceptions being swallowed in `element`/`nonza`/`stanza` handlers
- makes stanza handler behave like a proper EventEmitter handler.
- properly handle incoming malformed xml
- fix websocket framed parser malformed xml error
The original code was totally insane, no idea what happened with my brain there.
See https://github.com/xmppjs/xmpp.js/issues/792
Test case:
```js
/* eslint-disable node/no-extraneous-require */
'use strict'
const {client, xml} = require('@xmpp/client')
const debug = require('@xmpp/debug')
const xmpp = client({
service: 'ws://localhost:5280/ws',
domain: 'localhost',
resource: 'example',
username: 'username',
password: 'password',
})
debug(xmpp, true)
xmpp.reconnect.stop()
xmpp.on('stanza', stanza => {
// Throws
stanza.foo.hello()
}) …
```
=> connection: fix exceptions in data handlers

packages/client-core/lib/Client.js, packages/client/README.md, packages/component/README.md, packages/connection-tcp/index.js, packages/connection-tcp/test/Connection.js, packages/connection/index.js, packages/connection/test/send.js, packages/websocket/lib/Connection.js, packages/websocket/test/test.js
https://github.com/xmppjs/xmpp.js/pull/872 doesn't not work with WebSocket 
> The individual frames of a framed XML stream have a one-to-one
correspondence with WebSocket messages and MUST be parsable as
standalone XML documents
https://tools.ietf.org/html/rfc7395#section-3.3.3
So instead - we serialize and send multiple stanzas on TCP but send each stanza as a frame on WebSocket.
Because of complexitity involved - this feature is available as a new method `sendMultiple`.
=> sendMultiple

packages/resolve/lib/dns.js
See https://mail.jabber.org/pipermail/standards/2022-February/038759.html
Closes https://github.com/xmppjs/xmpp.js/issues/933
=> dns: Remove support for insecure TXT records

README.md
As many Github projects have features enabled that they don't use, some people (like me) don't bother flipping through all tabs on the Github project home page, assuming that most of them will be empty anyways. If I wasn't aware that the Discussions Github feature is actively being used by this project, then at least some portion of other newcomers likely won't be either.
This commit adds a stupidly simple pointer for "where do I go when I need help" as a new section in the readme, to help guide people like me.
=> Add 'Getting help' section to readme

packages/stream-management/index.js, packages/stream-management/test.js
Trying to await the sending of an "enable" stanza to fix a "Uncaught exception" (see #961).
The attempt is currently failing because I'm kind of a newbie regarding Ava and the testing framework.
I tried to write a test with a client that rejects the "send", but could not really manage to have that working.
I'm not 100% sure if I'm mocking the client correctly, nor if the error is supposed to be triggered by the "tick" function actually.
I'm also not sure I'm using `t.throwsAsync` correctly.
Also, adding the "await" keyword to "entity.send" is triggering other tests to fail.
Any pointer/idea/suggestion would be warmly welcome :pray:
=> stream-management: await the enable stanza
